# Generated by Django 4.2.7 on 2023-11-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worldpopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField()),
                ('pop1980', models.PositiveIntegerField()),
                ('pop2000', models.PositiveIntegerField()),
                ('pop2010', models.PositiveIntegerField()),
                ('pop2022', models.PositiveIntegerField()),
                ('pop2023', models.PositiveIntegerField()),
                ('pop2030', models.PositiveIntegerField()),
                ('pop2050', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=200, unique=True)),
                ('area', models.PositiveIntegerField()),
                ('landAreaKm', models.PositiveIntegerField()),
                ('cca2', models.CharField(max_length=200)),
                ('cca3', models.CharField(max_length=200)),
                ('netChange', models.PositiveIntegerField()),
                ('growthRate', models.PositiveIntegerField()),
                ('worldPercentage', models.PositiveIntegerField()),
                ('density', models.PositiveIntegerField()),
                ('densityMi', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
    ]
