# Generated by Django 4.2.7 on 2023-11-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpopulation',
            name='growthRate',
            field=models.PositiveBigIntegerField(),
        ),
    ]
