# Generated by Django 4.2.7 on 2023-11-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('population', '0003_alter_worldpopulation_density_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldpopulation',
            name='landAreaKm',
            field=models.FloatField(),
        ),
    ]
